version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  chatbot-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - HF_API_TOKEN=${HF_API_TOKEN}
    depends_on:
      - redis